# user variables, change this to make custom site.

name: Lemma
desc: Yet another simple theme for Jekyll.
author: neizod
baseurl: /lemma-theme


# system variables, do not change unless you knew what's it does.

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed
